### ISSUE TITLE
[BUG] A test throws warnings when it can't find the tree/songs.raml fixture.

### ISSUE THREAD

**Issue by CozyLife** [alecsammon/php-raml-parser#63] opened 2015-04-12 17:08 UTC
I just updated my software to your latest commit and I ran the tests. Below is the new output.

```
PHPUnit 4.6.2 by Sebastian Bergmann and contributors.

Configuration read from /var/www/api/fuel/vendor/alecsammon/php-raml-parser/phpunit.xml

...............................................................  63 / 108 ( 58%)
..................................PHP Warning:  Attempt to assign property of non-object in /var/www/api/fuel/vendor/justinrainbow/json-schema/src/JsonSchema/Uri/UriRetriever.php on line 141
.
Warning: Attempt to assign property of non-object in /var/www/api/fuel/vendor/justinrainbow/json-schema/src/JsonSchema/Uri/UriRetriever.php on line 141
PHP Warning:  file_get_contents(file:///var/www/api/fuel/vendor/alecsammon/php-raml-parser/test/fixture/tree/song.json): failed to open stream: No such file or directory in /var/www/api/fuel/vendor/justinrainbow/json-schema/src/JsonSchema/Uri/Retrievers/FileGetContents.php on line 36
.
Warning: file_get_contents(file:///var/www/api/fuel/vendor/alecsammon/php-raml-parser/test/fixture/tree/song.json): failed to open stream: No such file or directory in /var/www/api/fuel/vendor/justinrainbow/json-schema/src/JsonSchema/Uri/Retrievers/FileGetContents.php on line 36
.........

Time: 1.25 seconds, Memory: 15.00Mb

OK (108 tests, 244 assertions)
```

**Comment by alecsammon** [comment] 2015-04-12 17:11
Can you try
composer update
Then run the tests again.

**Comment by CozyLife** [comment] 2015-04-12 17:45
The only new update was for my framework. I updated before writing my posted, so I did get your update.

**Comment by alecsammon** [comment] 2015-04-13 08:19
This bug is a bit strange.

I'm not seeing it locally. And travis is also not seeing it https://travis-ci.org/alecsammon/php-raml-parser/builds/58093628.

The root cause is the version of json-schema you are using. I've made a couple of minor patches to the library to remove warnings, so you should be using my version. The most likely reason is that you are also including a version on json-schema elsewhere, so composer is not loading my version.

The best solution is to upgrade this library to use the latest version of https://github.com/justinrainbow/json-schema, and try and get my changes merged in. It looks like there is now some movement there, so will look into it more.

Will keep you updated.

**Comment by CozyLife** [comment] 2015-04-13 14:43
I'd feel more comfortable with rewriting the tests, or better yet making changes to the official json-schema repo to check if the file exists before attempting to load it. Then, just make a pull request.

I don't like having to patch unofficial code into third party code for a couple reasons. One, if the official code changes, it might not function with the patch anymore. Two, it requires extra work to keep changing the files every time when it doesn't need to be done.

**Comment by alecsammon** [comment] 2015-04-14 05:59
Ah - sorry. Don't think I've been very clear. 

I have made the changes on a fork of the official repo. There was an open pull request, but I've temporarily withdrawn it until I can tidy up my code.

In the composer.json for this repository it has an override to load my version of the json-schema library, instead of the official version. For some reason when you are using the library it is not loading my version (as it should be).

**Comment by CozyLife** [comment] 2015-04-14 14:33
In composer.json it says to use the [official repo's latest development version](https://github.com/alecsammon/php-raml-parser/blob/master/composer.json#L35). As your fork is at [alecsammon/json-schema](https://github.com/alecsammon/json-schema) the line should be changed to use the appropriate version of that repo.

**Closed** 2015-04-17 19:49 UTC
